---
author: "Robert Iagar"
baseurl: ""
description: "Student. .NET Developer. Amateur Photographer. Welcome to my blog!"
email: robert.iagar@gmail.com
github_username: robertiagar
highlighter: pygments
markdown: kramdown
permalink: none
title: "Robert's Blog"
twitter_username: robertiagar
url: "http://www.robertiagar.com"
paginate: 5
paginate_path: "/page:num"
defaults:
  -
   scope: 
     path: ""
     type: "post"
   values:
     author: "Robert Iagar"
     email: "robert.iagar@gmail.com"
     authorimageurl: "/assets/images/bg.jpg"
