--- 
author: "Robert Iagar"
baseurl: ""
description: "Student. .NET Developer. Amateur Photographer. Welcome to my blog."
email: robert.iagar@gmail.com
github_username: robertiagar
highlighter: pygments
markdown: kramdown
permalink: pretty
title: "Robert's Blog"
twitter_username: robertiagar
url: "http://robertigar.com"
