---
author: "Robert Iagar"
baseurl: ""
description: "Student. .NET Developer. Amateur Photographer. Welcome to my blog."
email: robert.iagar@gmail.com
github_username: robertiagar
highlighter: rouge
markdown: kramdown
permalink: pretty
title: "Robert's Blog"
twitter_username: robertiagar
url: "http://robertigar.com"
defaults:
   -
     scope:
       path: "posts"
       type: "page"
     values:
      layout: "post"
      author: "Robert Iagar"
      email: robert.iagar@gmail.com

