---
author: "Robert Iagar"
authorimageurl: "/assets/images/bg.jpg"
baseurl: ""
description: "Student. .NET Developer. Amateur Photographer. Welcome to my blog!"
email: robert.iagar@gmail.com
github_username: robertiagar
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
permalink: /:year/:month/:day/:title/
title: "Robert's Blog"
twitter_username: robertiagar
url: "http://www.robertiagar.com"
paginate: 5
paginate_path: "/page:num"
timezone: Europe/Bucharest
gems:
  - jemoji
  - jekyll-mentions
defaults:
  -
   scope:
     path: ""
     type: "posts"
   values:
     author: "Robert Iagar"
     email: "robert.iagar@gmail.com"
     authorimageurl: "/assets/images/bg.jpg"
     comments: true
